languauge: node_js
node_js:
  - 12.14.0
cache: npm

addons:
  chrome: stable

install:
  - npm ci

script:
  - npm test
  - npm build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master