languauge: node_js
node_js:
  - 12.14.0
env:
  global:
    -MOZ_HEADLESS=1

  addons:
    firefox: latest

cache: npm


install:
  - npm ci

before_script:
  - npm install -g @angular/cli

script:
  - ng test --watch=false
  - ng build --prod --base-href https://paisoemoe.github.io//travis/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/testing
  on:
    branch: master